name: Node.js CI/CD  
  
on:  
  push:  
    branches:  
      - main  
  
jobs:  
  build-and-deploy:  
    name: Build and Deploy Node.js App  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@main  
      - name: Install Node.js and Dependencies  
        run: |  
          sudo apt-get update -y  
          sudo apt-get install -y nodejs npm  
          npm install  
      - name: Start Node.js App  
        run: npm start
