name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build Application
        run: npm run build
      
      - name: Start Application in Background
        run: node app.js & echo $! > .pidfile
        outputs:
          pid: .pidfile
      
      - name: Monitor and Restart Application
        if: always()
        run: |
          while true; do
            sleep 5m
            if ! test -f .pidfile; then
              echo "Application exited, restarting..."
              node app.js & echo $! > .pidfile
            fi
          done
